### ISSUE TITLE
Error: Cannot find module './firebase.json'

### ISSUE THREAD

**Issue by luisfrt** [johnwargo/firebase-functions-deploy-helper#1]
Hi! I am getting this error when I run the command "ffdh -b 4".

```
Firebase Functions Deploy Helper (ffdh)
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './firebase.json'
Require stack:
- /usr/local/lib/node_modules/firebase-functions-deploy-helper/ffdh.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at isValidConfig (/usr/local/lib/node_modules/firebase-functions-deploy-helper/ffdh.js:72:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-functions-deploy-helper/ffdh.js:160:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/firebase-functions-deploy-helper/ffdh.js'
  ]
}
```

My firebase.json file is like this:
```
{
  "functions": {
   "predeploy": [
     "npm --prefix \"$RESOURCE_DIR\" run lint"
   ]
  }
}

```

Any ideas on how to solve this?

**Comment by johnwargo** [comment]
The module's trying to read the `firebase.json` file to determine the functions source folder - your file doesn't have one.  Mine looks like this:

```json
{
"functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ],
    "source": "functions"
  },
}
```

**Comment by johnwargo** [comment]
ooh, it looks like Firebase removed that setting from the file. Interesting. I just created a new project and its not there in the new project's firebase.json. I guess I can assume a value of functions if its not in the file. Let me play around with this.

**Comment by johnwargo** [comment]
Can you please run the command with a `-d` (debug) and share the output here?  I think there's something else going on here and I want to make sure I get you a solid fix.

**Comment by johnwargo** [comment]
@luisfrt I just published an update that fixes the issue with the `source` property not being set. I'm not sure if this will fix the actual issue you're experiencing. Please send me the debug output from this new version and we'll see if it fixes your problem

**Comment by johnwargo** [comment]
@luisfrt I've not seen a response from you, can you please respond?

**Comment by johnwargo** [comment]
Closed due to lack of response from submitter,
